# FROM gcr.io/cloud-datalab/datalab:latest
FROM gcr.io/cloud-datalab/datalab:commit-latest-master-build

MAINTAINER Cong Vo <kongvc@gmail.com>

COPY ./custom /custom
RUN cd /custom &&\
    ./install.sh &&\
    ./cleanup.sh
