# FROM gcr.io/cloud-datalab/datalab:latest
FROM gcr.io/cloud-datalab/datalab:commit-latest-master-build

MAINTAINER Cong Vo <kongvc@gmail.com>

COPY custom-packages.sh /datalab/
RUN /datalab/custom-packages.sh
